---
# tasks file for clean_env
- name: Uninstall Grafana
  ansible.builtin.import_tasks: uninstall_grafana.yml
  when: "clean_env_uninstall_grafana"

- name: Uninstall Prometheus
  ansible.builtin.import_tasks: uninstall_prometheus.yml
  when: "clean_env_uninstall_prometheus"

- name: Uninstall Loki
  ansible.builtin.import_tasks: uninstall_loki.yml
  when: "clean_env_uninstall_loki"

- name: Uninstall OTEL Collector
  ansible.builtin.import_tasks: uninstall_otelcol.yml
  when: "clean_env_uninstall_otelcol"

- name: Uninstall Jaeger
  ansible.builtin.import_tasks: uninstall_jaeger.yml
  when: "clean_env_uninstall_jaeger"

- name: Uninstall Grafana Tempo
  ansible.builtin.import_tasks: uninstall_tempo.yml
  when: "clean_env_uninstall_tempo"

- name: Uninstall VictoriaMetrics
  ansible.builtin.import_tasks: uninstall_victoriametrics.yml
  when: "clean_env_uninstall_victoriametrics"

- name: Reboot server
  ansible.builtin.reboot:
  become: true
