---
- name: Testing variables
  debug:
    msg:
      "collector_version": "{{ collector_version }}"
      "package_url": "{{ package_url }}"
      "builder_binary_url": "{{ builder_binary_url }}"
      "go_sdk_package_url": "{{ go_sdk_package_url }}"
      "install_arch": "{{ install_arch }}"

- name: Unpack GO SDK package
  ansible.builtin.unarchive:
    src: "{{ go_sdk_package_url }}"
    dest: "{{ install_dir }}/tools"
    mode: '0755'
    owner: otel
    group: otel
    remote_src: true
  become: true

- name: List Go SDK files
  shell: "ls -lha {{ install_dir }}/tools"
  environment:
    MY_ENV_VARIABLE: whatever_value

- name: Debug Go version
  shell: "go version"
  environment:
    PATH: "$PATH:{{ install_dir }}/tools/go/bin"
  register: go_version_res

- name: Debug Go version
  debug:
    msg: "{{ go_version_res.stdout_lines }}"

- name: Debug PATH variable
  shell: "echo $PATH"
  environment:
    PATH: "$PATH:{{ install_dir }}/tools/go/bin"
  register: path_variable_res

- name: Debug PATH variable
  debug:
    msg: "{{ path_variable_res.stdout_lines }}"



- name: Download OTEL Collector Builder
  ansible.builtin.get_url:
    url: "{{ builder_binary_url }}"
    dest: "{{ install_dir }}/tools/ocb"
    mode: '0755'
    owner: otel
    group: otel
  become: true

- name: Generate otelcol-builder.yaml file
  ansible.builtin.template:
    src: otelcol-builder.yaml
    dest: "{{ install_dir }}/conf/otelcol-builder.yaml"
    owner: otel
    group: otel
  become: true
  register: config_task_res

- name: Build OTEL Collector
  shell: "{{ install_dir }}/tools/ocb --config {{ install_dir }}/conf/otelcol-builder.yaml"
  environment:
    PATH: "$PATH:{{ install_dir }}/tools/go/bin"
    GOCACHE: "{{ install_dir }}/tmp"
  register: otelcol_build_res
  become: true

- name: Change collector binary ownership
  file:
    path: "{{ install_dir }}/bin/otelcol"
    state: file
    owner: otel
    group: otel
    mode: "0755"

- name: Build output
  debug:
    msg: "{{ otelcol_build_res.stdout_lines }}"

# - name: Building OTEL Collector
#   shell: "echo $MY_ENV_VARIABLE"
#   environment:
#     PATH: "$PATH:{{ install_dir }}/tools/go/bin"
