---
# tasks file for otel_collector
- name: Install OTEL Collector package
  ansible.builtin.apt:
    deb: "{{ package_url }}"
  become: true
  notify:
    - Restart Collector

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: otel
    group: otel
  become: true
  loop:
    - "/etc/otelcol"


- name: Generate config.yaml file
  ansible.builtin.template:
    src: config.yaml
    dest: /etc/otelcol/config.yaml
    owner: otel
    group: otel
  become: true
  register: config_task_res
  notify:
    - Restart Collector

# - name: Wait until OTEL Collector is up and running...
#   uri:
#     url: 'http://{{ ansible_default_ipv4.address }}:3100/ready'
#     return_content: yes
#     validate_certs: no
#     status_code:
#       - 200
#   until: uri_output.status == 200
#   retries: 24 # Retries for 24 * 15 seconds = 360 seconds = 6 minutes
#   delay: 15 # Every 15 seconds
#   register: uri_output

# - name: API test result
#   debug:
#     msg: "{{ uri_output }}"
