---
# tasks file for otel_collector
- name: Install OTEL Collector package
  ansible.builtin.apt:
    deb: "{{ package_url }}"
  become: true
  notify:
    - Restart Collector

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: otel
    group: otel
  become: true
  loop:
    - "/etc/otelcol"


- name: Generate config.yaml file
  ansible.builtin.template:
    src: config.yaml
    dest: /etc/otelcol/config.yaml
    owner: otel
    group: otel
  become: true
  register: config_task_res
  notify:
    - Restart Collector
