---
receivers:
  fluentforward:
    endpoint: 127.0.0.1:6543
  otlp/traces:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55689
  otlp/metrics:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55690


processors:
  batch:
  resource:
    attributes:
    - action: insert
      key: loki.format
      value: json

exporters:
  otlp/jaeger: # Jaeger supports OTLP directly
    endpoint: {{ ansible_default_ipv4.address }}:4317
    tls:
      insecure: true
      insecure_skip_verify: true
  prometheusremotewrite:
    endpoint: http://{{ ansible_default_ipv4.address }}:9009/api/v1/push
    tls:
      insecure: true
      insecure_skip_verify: true
    resource_to_telemetry_conversion:
      enabled: false # Convert resource attributes to metric labels
  otlp/tempo:
    endpoint: {{ ansible_default_ipv4.address }}:5317
    tls:
      insecure: true
      insecure_skip_verify: true
  otlphttp/loki:
    endpoint: http://{{ ansible_default_ipv4.address }}:3100/otlp/v1/logs

service:
  pipelines:
    traces/otlp:
      receivers: [otlp/traces]
      processors: [batch]
      exporters: [otlp/jaeger, otlp/tempo]
    metrics/otlp:
      receivers: [otlp/metrics]
      processors: [batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [fluentforward]
      processors: [batch]
      exporters: [otlphttp/loki]
  extensions: [health_check, pprof, zpages]

extensions:
  pprof:
  zpages:
  health_check:
    endpoint: "localhost:13133"
    path: "/health/status"
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5
