---
receivers:
  otlp/traces:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55689
  otlp/metrics:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55690

processors:
  batch:

exporters:
  otlp/jaeger: # Jaeger supports OTLP directly
    endpoint: {{ ansible_default_ipv4.address }}:4317
    tls:
      insecure: true
      insecure_skip_verify: true
  prometheusremotewrite:
    endpoint: http://{{ ansible_default_ipv4.address }}:9009/api/v1/push
    tls:
      insecure: true
      insecure_skip_verify: true
    resource_to_telemetry_conversion:
      enabled: false # Convert resource attributes to metric labels
  otlp/tempo:
    endpoint: {{ ansible_default_ipv4.address }}:5317
    tls:
      insecure: true
      insecure_skip_verify: true

service:
  pipelines:
    traces/otlp:
      receivers: [otlp/traces]
      processors: [batch]
      exporters: [otlp/jaeger, otlp/tempo]
    metrics/otlp:
      receivers: [otlp/metrics]
      processors: [batch]
      exporters: [prometheusremotewrite]
  extensions: [health_check, pprof, zpages]

extensions:
  pprof:
  zpages:
  health_check:
    endpoint: "localhost:13133"
    path: "/health/status"
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5
