---
receivers:
  otlp/traces:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55689
  otlp/metrics:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55690

processors:
  batch:

exporters:
  otlp/jaeger: # Jaeger supports OTLP directly
    endpoint: {{ ansible_default_ipv4.address }}:4317
    tls:
      insecure: true
      insecure_skip_verify: true
  # prometheus:
    # endpoint: "0.0.0.0:9089"
  prometheusremotewrite:
    endpoint: http://{{ ansible_default_ipv4.address }}:9090
  otlp/tempo:
    endpoint: {{ ansible_default_ipv4.address }}:5317
    tls:
      insecure: true
      insecure_skip_verify: true

service:
  pipelines:
    traces/dev:
      receivers: [otlp/traces]
      processors: [batch]
      exporters: [otlp/jaeger, otlp/tempo]
    metrics/prod:
      receivers: [otlp/metrics]
      processors: [batch]
      exporters: [prometheusremotewrite]
      # exporters: [prometheus]
  extensions: [health_check, pprof, zpages]

extensions:
  pprof:
  zpages:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health/status"
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5
