---
- name: Create Jaeger user group
  ansible.builtin.group:
    name: jaeger
    state: present
  become: true
  notify:
    - Restart Jaeger

- name: Create Jaeger system user
  ansible.builtin.user:
    name: jaeger
    comment: Jaeger service user
    group: jaeger
    state: present
    system : true
  become: true
  notify:
    - Restart Jaeger

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: directory
    mode: '0755'
    owner: jaeger
    group: jaeger
  become: true
  notify:
    - Restart Jaeger

- name: Unpack Jaeger bin package
  ansible.builtin.unarchive:
    src: "{{ download_url }}"
    dest: "{{ install_dir }}"
    mode: '0755'
    owner: jaeger
    group: jaeger
    remote_src: true
    extra_opts:
      - '--strip-components=1'
      - '--show-stored-names'
  become: true
  notify:
    - Restart Jaeger

- name: Create service definition file
  ansible.builtin.template:
    src: jaeger.service.j2
    dest: /etc/systemd/system/jaeger.service
    owner: root
    group: root
  become: true
  notify:
    - Restart Jaeger
