---
# vars file for prometheus
prometheus_version: 2.52.0
download_url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-arm64.tar.gz
install_dir: /usr/local/prometheus
remote_write_enabled: true
