---
# tasks file for prometheus
- name: Create Prometheus user group
  ansible.builtin.group:
    name: prometheus
    state: present
  become: true
  notify:
    - Restart Prometheus

- name: Create Prometheus system user
  ansible.builtin.user:
    name: prometheus
    comment: Prometheus service user
    group: prometheus
    state: present
    system : true
  become: true
  notify:
    - Restart Prometheus

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: directory
    mode: '0755'
    owner: prometheus
  become: true
  notify:
    - Restart Prometheus

- name: Unpack Prometheus bin package
  ansible.builtin.unarchive:
    src: "{{ download_url }}"
    dest: "{{ install_dir }}"
    mode: '0755'
    owner: prometheus
    remote_src: true
    extra_opts:
      - '--strip-components=1'
      - '--show-stored-names'
  become: true
  notify:
    - Restart Prometheus

- name: Create service definition file
  ansible.builtin.template:
    src: prometheus.yaml
    dest: /usr/local/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
  become: true
  notify:
    - Restart Prometheus

- name: Create service definition file
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
  become: true
  notify:
    - Restart Prometheus
