---
- hosts: prometheus
  roles:
    - role: "roles/otel_collector"
      vars:
        otel_collector_fluentforward_receiver_enabled: false
        otel_collector_otlptraces_receiver_enabled: true
        otel_collector_otlpmetrics_receiver_enabled: true
        otel_collector_loki_exporter_enabled: true
        otel_collector_tempo_exporter_enabled: false
        otel_collector_jaeger_exporter_enabled: true
        otel_collector_prometheus_remotewrite_enabled: false
        otel_collector_victoriametrics_exporter_enabled: true
