---
- name: Installs Prometheus environment
  hosts: prometheus
  roles:
    # - role: "roles/clean_env"
    - role: "roles/prepare_os"
    - role: "roles/grafana_loki"
    - role: "roles/jaeger"
    - role: "roles/prometheus"
    - role: "roles/grafana_tempo"
    - role: "roles/grafana"
    - role: "roles/otel_collector"
