---
- name: Installs VictoriaMetrics
  hosts: prometheus
  roles:
    - role: "victoriametrics.cluster.single"
      become: true
      vars:
        victoriametrics_system_user: "victoria"
        victoriametrics_system_group: "{{ victoriametrics_system_user }}"
        victoriametrics_delete_auth_key: "123P@ss"
        victoriametrics_snapshot_auth_key: "123P@ss"
        victoriametrics_install_vmutil: true
        victoriametrics_service_args:
          storageDataPath: "{{ victoriametrics_data_dir }}"
          selfScrapeInterval: "{{ victoriametrics_self_scrape_interval }}"
          retentionPeriod: "{{ victoriametrics_retention_period_months }}"
          maxConcurrentInserts: 32
          "search.maxUniqueTimeseries": "{{ victoriametrics_search_max_unique_timeseries }}"
          "vmalert.proxyURL": "http://192.168.0.68:8428/vmalert/"

      no_log: false
