---
- name: Installs VictoriaMetrics
  hosts: prometheus
  roles:
    - role: "victoriametrics.cluster.single"
      become: true
      vars:
        victoriametrics_system_user: "victoria"
        victoriametrics_system_group: "{{ victoriametrics_system_user }}"
        victoriametrics_delete_auth_key: "123P@ss"
        victoriametrics_snapshot_auth_key: "123P@ss"
        victoriametrics_install_vmutil: true
        victoriametrics_data_dir: /usr/local/victoriametrics
        victoriametrics_self_scrape_interval: "30s"
        victoriametrics_search_max_unique_timeseries: "300000"
        victoriametrics_service_args:
          storageDataPath: "{{ victoriametrics_data_dir }}/data"
          selfScrapeInterval: "{{ victoriametrics_self_scrape_interval }}"
          retentionPeriod: "1"
          maxConcurrentInserts: 8
          "search.maxUniqueTimeseries": "{{ victoriametrics_search_max_unique_timeseries }}"
          "vmui.customDashboardsPath": "{{ victoriametrics_data_dir }}/dashboards"

      no_log: false
